# -*- coding: utf-8 -*-
"""Orlando's calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pkA0d59pTQ9s-lX8lev2scllyjAifuFa
"""

# projeto de calculadora

print("Bem vindo a essa belíssima e básica calculadora!")
print("Instruções: Use ponto(.) para números reais.")

reiniciar = "S"
while (reiniciar == "S") or (reiniciar == "s"):


  valor1 = input("Insira o primeiro valor: ") # recebe primeiro valor
  valor1 = float(valor1)

  operacoes = ['1-Soma', '2-Subtração', '3-Multiplicação', '4-Divisão', '5-Potencia', '6-Raiz'] #listagem das operações disponíveis
  print("Digite o valor correspondente a operação que deseja realizar:\n",operacoes[0], operacoes[1], operacoes[2], operacoes[3], operacoes[4], operacoes[5])
  operacao = input() #recebe a operação a ser realizada
  operacao = int(operacao)

  valor2 = input("Insira o segundo valor: ") # recebe segundo valor
  valor2 = float(valor2)

  print("Primeiro valor:", valor1)
  print("Segundo valor:", valor2)
  print("Operação escolhida:", operacoes[int(operacao)-1])


  if operacao == 1:
    resultado = valor1 + valor2
  elif operacao == 2:
    resultado = valor1 - valor2
  elif operacao == 3:
    resultado = valor1 * valor2
  elif operacao == 4:
    resultado = valor1 / valor2
  elif operacao == 5:
    resultado = valor1 ** valor2
  elif operacao == 6:
    resultado = valor1 ** (1/valor2)


  print("O resultado da operação", operacoes[int(operacao)-1], "é", resultado,".")


  reiniciar = input ("Deseja iniciar um novo cálculo? S/N ")
  reiniciar = str(reiniciar)

else:
  print("Obrigado por usar a nossa calculadora, até breve.")

